---
    - name: Create public IP address "{{ public_ip_name }}"
      azure_rm_publicipaddress:
        resource_group:  "{{resource_group_name}}"
        allocation_method: Static
        name: "{{ public_ip_name }}"
        sku: standard
      register: output_ip_address
    - debug:
        msg: "The public IP generated for {{ public_ip_name }} is {{ output_ip_address.state.ip_address }}"