---
    - name: Create virtual network "{{ virtual_network_name }}"
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ virtual_network_name }}"
        address_prefixes: "{{ virtual_network_cidr }}"