- name: Azure VPN P2S Gateway & Client setup
  hosts: localhost
  connection: local
  vars:
    resource_group_name: az-vpn-gw-rg
    region: centralindia
    virtual_network_name: az-vpn-gw-vnet
    virtual_network_cidr: "10.1.0.0/16"
    subnet_name: GatewaySubnet
    subnet_range: "10.1.1.0/24"
    public_ip_name: az-vpn-gw-pip
    vpn_gateway_name: az-vpn-gateway
    az_client_id: <<azure client id>>
    az_client_secret: << azure client secret>>
    az_tenant_id: << azure tenant id >>
  roles:
    - az-resource-group
    - az-virtual-network
    - az-subnet
    - az-public-ip
    - az-virtual-network-gateway
    - az-vpn-p2s-connection


