---
# handlers file for db
- name: start mysql
  service: name=mysql
           enabled=yes
           state=started
- name: restart mysql
  service: name=mysql
           enabled=yes
           state=restarted