---
    - name: Install MySQL database
      apt: name={{ item }} state=present force=yes
      with_items:
        - mariadb-server
    
    - name: Install PyMySQL
      pip: name={{ item }} state=present
      with_items:
        - pymysql

    - name: Update MySQL Configuration file to accept connections from all interfaces
      ini_file:
        path:  "{{item}}"
        section: mysqld
        option: bind-address
        value: 0.0.0.0
      with_items:
        - /etc/mysql/mariadb.conf.d/50-server.cnf
        - /etc/mysql/my.cnf

    - name: Create `/root/.my.cnf` with root password credentials
      template:
        src:  my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0660
      become: yes
      notify: restart mysql
    
    - name: Cretae Database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: "*.*:ALL"
        state: present
        host: '%'
        login_unix_socket: /var/run/mysqld/mysqld.sock
      notify: start mysql

    
    - name: Create Application Database
      mysql_db: 
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock   