---
    - name: Create VM "{{ vm_name }}"
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ key_data }}"
        network_interfaces: "{{ nic_name }}"
        image:
          offer: debian-10
          publisher: Debian
          sku: '10'
          version: latest
      register: vm_output
    - debug:
        var=vm_output